name: Dart CI

env:
  DART_VERSION_LATEST: "latest"
  DART_VERSION_PREV: "3.10.9"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_dart_latest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION_LATEST }}
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: Ensure dependencies upgrated
        run: dart pub upgrade
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Activate webdev
        run: dart pub global activate webdev
      - name: webdev build
        run: webdev build --release
      - name: dart compile wasm
        run: dart compile wasm web/main.dart -o build/main.wasm --verbose

  build_dart_prev:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION_PREV }}
      - name: Dart version
        run: |
          dart --version
          uname -a
      - name: Install dependencies
        run: dart pub get
      - name: Ensure dependencies upgrated
        run: dart pub upgrade
      - name: dart format
        run: dart format -o none --set-exit-if-changed .
      - name: dart analyze
        run: dart analyze --fatal-infos --fatal-warnings .
      - name: Activate webdev
        run: dart pub global activate webdev
      - name: webdev build
        run: webdev build --release
      - name: dart compile wasm
        run: dart compile wasm web/main.dart -o build/main.wasm --verbose

